/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][4];
new PlayerText:businessBox[MAX_PLAYERS];
new PlayerText:addressString[MAX_PLAYERS];
new PlayerText:addressStatus[MAX_PLAYERS];
new PlayerText:addressType[MAX_PLAYERS];
new PlayerText:addressPrice[MAX_PLAYERS];
new PlayerText:addressName[MAX_PLAYERS];
new PlayerText:addressNameString[MAX_PLAYERS];

//Textdraws

//Player Textdraws
businessBox[playerid] = CreatePlayerTextDraw(playerid, 63.000000, 141.000000, "`");
PlayerTextDrawFont(playerid, businessBox[playerid], 0);
PlayerTextDrawLetterSize(playerid, businessBox[playerid], 0.600000, 10.400004);
PlayerTextDrawTextSize(playerid, businessBox[playerid], 206.500000, 5.000000);
PlayerTextDrawSetOutline(playerid, businessBox[playerid], 1);
PlayerTextDrawSetShadow(playerid, businessBox[playerid], 0);
PlayerTextDrawAlignment(playerid, businessBox[playerid], 1);
PlayerTextDrawColor(playerid, businessBox[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, businessBox[playerid], 255);
PlayerTextDrawBoxColor(playerid, businessBox[playerid], 50);
PlayerTextDrawUseBox(playerid, businessBox[playerid], 1);
PlayerTextDrawSetProportional(playerid, businessBox[playerid], 1);
PlayerTextDrawSetSelectable(playerid, businessBox[playerid], 0);

addressString[playerid] = CreatePlayerTextDraw(playerid, 66.000000, 158.000000, "Address:");
PlayerTextDrawFont(playerid, addressString[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressString[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressString[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressString[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressString[playerid], 0);
PlayerTextDrawAlignment(playerid, addressString[playerid], 1);
PlayerTextDrawColor(playerid, addressString[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, addressString[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressString[playerid], 50);
PlayerTextDrawUseBox(playerid, addressString[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressString[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressString[playerid], 0);

addressStatus[playerid] = CreatePlayerTextDraw(playerid, 76.000000, 175.000000, "Status:");
PlayerTextDrawFont(playerid, addressStatus[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressStatus[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressStatus[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressStatus[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressStatus[playerid], 0);
PlayerTextDrawAlignment(playerid, addressStatus[playerid], 1);
PlayerTextDrawColor(playerid, addressStatus[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, addressStatus[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressStatus[playerid], 50);
PlayerTextDrawUseBox(playerid, addressStatus[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressStatus[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressStatus[playerid], 0);

addressType[playerid] = CreatePlayerTextDraw(playerid, 84.000000, 191.000000, "Type:");
PlayerTextDrawFont(playerid, addressType[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressType[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressType[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressType[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressType[playerid], 0);
PlayerTextDrawAlignment(playerid, addressType[playerid], 1);
PlayerTextDrawColor(playerid, addressType[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, addressType[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressType[playerid], 50);
PlayerTextDrawUseBox(playerid, addressType[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressType[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressType[playerid], 0);

addressPrice[playerid] = CreatePlayerTextDraw(playerid, 83.000000, 211.000000, "Price:");
PlayerTextDrawFont(playerid, addressPrice[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressPrice[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressPrice[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressPrice[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressPrice[playerid], 0);
PlayerTextDrawAlignment(playerid, addressPrice[playerid], 1);
PlayerTextDrawColor(playerid, addressPrice[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, addressPrice[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressPrice[playerid], 50);
PlayerTextDrawUseBox(playerid, addressPrice[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressPrice[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressPrice[playerid], 0);

PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 125.000000, 158.000000, "3000.street");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 125.000000, 176.000000, "For Sale");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 125.000000, 194.000000, "Business");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 125.000000, 212.000000, "$100000");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

addressName[playerid] = CreatePlayerTextDraw(playerid, 66.000000, 142.000000, "Name:");
PlayerTextDrawFont(playerid, addressName[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressName[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressName[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressName[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressName[playerid], 0);
PlayerTextDrawAlignment(playerid, addressName[playerid], 1);
PlayerTextDrawColor(playerid, addressName[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, addressName[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressName[playerid], 50);
PlayerTextDrawUseBox(playerid, addressName[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressName[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressName[playerid], 0);

addressNameString[playerid] = CreatePlayerTextDraw(playerid, 106.000000, 142.000000, "Hardware Store");
PlayerTextDrawFont(playerid, addressNameString[playerid], 1);
PlayerTextDrawLetterSize(playerid, addressNameString[playerid], 0.345833, 1.799998);
PlayerTextDrawTextSize(playerid, addressNameString[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, addressNameString[playerid], 1);
PlayerTextDrawSetShadow(playerid, addressNameString[playerid], 0);
PlayerTextDrawAlignment(playerid, addressNameString[playerid], 1);
PlayerTextDrawColor(playerid, addressNameString[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, addressNameString[playerid], 255);
PlayerTextDrawBoxColor(playerid, addressNameString[playerid], 50);
PlayerTextDrawUseBox(playerid, addressNameString[playerid], 0);
PlayerTextDrawSetProportional(playerid, addressNameString[playerid], 1);
PlayerTextDrawSetSelectable(playerid, addressNameString[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
