/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:dash1[MAX_PLAYERS];
new PlayerText:dash2[MAX_PLAYERS];
new PlayerText:dashPlate[MAX_PLAYERS];
new PlayerText:dashSpeed[MAX_PLAYERS];
new PlayerText:dashDist[MAX_PLAYERS];
new PlayerText:dashVid[MAX_PLAYERS];

//Textdraws

//Player Textdraws
dash1[playerid] = CreatePlayerTextDraw(playerid, 129.000000, 113.000000, "dashcam");
PlayerTextDrawFont(playerid, dash1[playerid], 2);
PlayerTextDrawLetterSize(playerid, dash1[playerid], 0.295832, 1.750000);
PlayerTextDrawTextSize(playerid, dash1[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dash1[playerid], 1);
PlayerTextDrawSetShadow(playerid, dash1[playerid], 0);
PlayerTextDrawAlignment(playerid, dash1[playerid], 1);
PlayerTextDrawColor(playerid, dash1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dash1[playerid], 255);
PlayerTextDrawBoxColor(playerid, dash1[playerid], 50);
PlayerTextDrawUseBox(playerid, dash1[playerid], 0);
PlayerTextDrawSetProportional(playerid, dash1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dash1[playerid], 0);

dash2[playerid] = CreatePlayerTextDraw(playerid, 129.000000, 129.000000, "CAM01");
PlayerTextDrawFont(playerid, dash2[playerid], 2);
PlayerTextDrawLetterSize(playerid, dash2[playerid], 0.295832, 1.750000);
PlayerTextDrawTextSize(playerid, dash2[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dash2[playerid], 1);
PlayerTextDrawSetShadow(playerid, dash2[playerid], 0);
PlayerTextDrawAlignment(playerid, dash2[playerid], 1);
PlayerTextDrawColor(playerid, dash2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dash2[playerid], 255);
PlayerTextDrawBoxColor(playerid, dash2[playerid], 50);
PlayerTextDrawUseBox(playerid, dash2[playerid], 0);
PlayerTextDrawSetProportional(playerid, dash2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dash2[playerid], 0);

dashPlate[playerid] = CreatePlayerTextDraw(playerid, 189.000000, 358.000000, "P PLATEHERE");
PlayerTextDrawFont(playerid, dashPlate[playerid], 2);
PlayerTextDrawLetterSize(playerid, dashPlate[playerid], 0.279166, 1.750000);
PlayerTextDrawTextSize(playerid, dashPlate[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashPlate[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashPlate[playerid], 0);
PlayerTextDrawAlignment(playerid, dashPlate[playerid], 1);
PlayerTextDrawColor(playerid, dashPlate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashPlate[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashPlate[playerid], 50);
PlayerTextDrawUseBox(playerid, dashPlate[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashPlate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashPlate[playerid], 0);

dashSpeed[playerid] = CreatePlayerTextDraw(playerid, 291.000000, 358.000000, "S 90MPH");
PlayerTextDrawFont(playerid, dashSpeed[playerid], 2);
PlayerTextDrawLetterSize(playerid, dashSpeed[playerid], 0.279166, 1.750000);
PlayerTextDrawTextSize(playerid, dashSpeed[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashSpeed[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashSpeed[playerid], 0);
PlayerTextDrawAlignment(playerid, dashSpeed[playerid], 1);
PlayerTextDrawColor(playerid, dashSpeed[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashSpeed[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashSpeed[playerid], 50);
PlayerTextDrawUseBox(playerid, dashSpeed[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashSpeed[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashSpeed[playerid], 0);

dashDist[playerid] = CreatePlayerTextDraw(playerid, 410.000000, 358.000000, "D 25M");
PlayerTextDrawFont(playerid, dashDist[playerid], 2);
PlayerTextDrawLetterSize(playerid, dashDist[playerid], 0.279166, 1.750000);
PlayerTextDrawTextSize(playerid, dashDist[playerid], 398.000000, 8.000000);
PlayerTextDrawSetOutline(playerid, dashDist[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashDist[playerid], 0);
PlayerTextDrawAlignment(playerid, dashDist[playerid], 3);
PlayerTextDrawColor(playerid, dashDist[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashDist[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashDist[playerid], 50);
PlayerTextDrawUseBox(playerid, dashDist[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashDist[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashDist[playerid], 0);

dashVid[playerid] = CreatePlayerTextDraw(playerid, 411.000000, 115.000000, "VID: vehId");
PlayerTextDrawFont(playerid, dashVid[playerid], 2);
PlayerTextDrawLetterSize(playerid, dashVid[playerid], 0.295832, 1.750000);
PlayerTextDrawTextSize(playerid, dashVid[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashVid[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashVid[playerid], 0);
PlayerTextDrawAlignment(playerid, dashVid[playerid], 3);
PlayerTextDrawColor(playerid, dashVid[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashVid[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashVid[playerid], 50);
PlayerTextDrawUseBox(playerid, dashVid[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashVid[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashVid[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
