/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:dashBox;
new PlayerText:dashTex[MAX_PLAYERS];
new PlayerText:dashName[MAX_PLAYERS];
new PlayerText:dashPlate[MAX_PLAYERS];
new PlayerText:dashOwner[MAX_PLAYERS];
new PlayerText:dashNameString[MAX_PLAYERS];
new PlayerText:dashPlateString[MAX_PLAYERS];
new PlayerText:dashOwnerString[MAX_PLAYERS];

//Textdraws
dashBox = TextDrawCreate(434.000000, 145.000000, "`");
TextDrawFont(dashBox, 2);
TextDrawLetterSize(dashBox, 0.600000, 12.599991);
TextDrawTextSize(dashBox, 605.500000, 52.000000);
TextDrawSetOutline(dashBox, 1);
TextDrawSetShadow(dashBox, 0);
TextDrawAlignment(dashBox, 1);
TextDrawColor(dashBox, -2686721);
TextDrawBackgroundColor(dashBox, 255);
TextDrawBoxColor(dashBox, 50);
TextDrawUseBox(dashBox, 1);
TextDrawSetProportional(dashBox, 1);
TextDrawSetSelectable(dashBox, 0);


//Player Textdraws
dashTex[playerid] = CreatePlayerTextDraw(playerid, 440.000000, 149.000000, "DASHCAM");
PlayerTextDrawFont(playerid, dashTex[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashTex[playerid], 0.554166, 2.000000);
PlayerTextDrawTextSize(playerid, dashTex[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashTex[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashTex[playerid], 0);
PlayerTextDrawAlignment(playerid, dashTex[playerid], 1);
PlayerTextDrawColor(playerid, dashTex[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, dashTex[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashTex[playerid], 50);
PlayerTextDrawUseBox(playerid, dashTex[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashTex[playerid], 0);
PlayerTextDrawSetSelectable(playerid, dashTex[playerid], 0);

dashName[playerid] = CreatePlayerTextDraw(playerid, 440.000000, 173.000000, "NAME:");
PlayerTextDrawFont(playerid, dashName[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashName[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, dashName[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashName[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashName[playerid], 0);
PlayerTextDrawAlignment(playerid, dashName[playerid], 1);
PlayerTextDrawColor(playerid, dashName[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, dashName[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashName[playerid], 50);
PlayerTextDrawUseBox(playerid, dashName[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashName[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashName[playerid], 0);

dashPlate[playerid] = CreatePlayerTextDraw(playerid, 440.000000, 198.000000, "PLATE:");
PlayerTextDrawFont(playerid, dashPlate[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashPlate[playerid], 0.587500, 2.000000);
PlayerTextDrawTextSize(playerid, dashPlate[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashPlate[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashPlate[playerid], 0);
PlayerTextDrawAlignment(playerid, dashPlate[playerid], 1);
PlayerTextDrawColor(playerid, dashPlate[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, dashPlate[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashPlate[playerid], 50);
PlayerTextDrawUseBox(playerid, dashPlate[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashPlate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashPlate[playerid], 0);

dashOwner[playerid] = CreatePlayerTextDraw(playerid, 440.000000, 224.000000, "OWNER:");
PlayerTextDrawFont(playerid, dashOwner[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashOwner[playerid], 0.462500, 2.049999);
PlayerTextDrawTextSize(playerid, dashOwner[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashOwner[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashOwner[playerid], 0);
PlayerTextDrawAlignment(playerid, dashOwner[playerid], 1);
PlayerTextDrawColor(playerid, dashOwner[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, dashOwner[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashOwner[playerid], 50);
PlayerTextDrawUseBox(playerid, dashOwner[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashOwner[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashOwner[playerid], 0);

dashNameString[playerid] = CreatePlayerTextDraw(playerid, 508.000000, 174.000000, "VEHNAME");
PlayerTextDrawFont(playerid, dashNameString[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashNameString[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, dashNameString[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashNameString[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashNameString[playerid], 0);
PlayerTextDrawAlignment(playerid, dashNameString[playerid], 1);
PlayerTextDrawColor(playerid, dashNameString[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashNameString[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashNameString[playerid], 50);
PlayerTextDrawUseBox(playerid, dashNameString[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashNameString[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashNameString[playerid], 0);

dashPlateString[playerid] = CreatePlayerTextDraw(playerid, 508.000000, 199.000000, "VPLATE");
PlayerTextDrawFont(playerid, dashPlateString[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashPlateString[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, dashPlateString[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashPlateString[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashPlateString[playerid], 0);
PlayerTextDrawAlignment(playerid, dashPlateString[playerid], 1);
PlayerTextDrawColor(playerid, dashPlateString[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashPlateString[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashPlateString[playerid], 50);
PlayerTextDrawUseBox(playerid, dashPlateString[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashPlateString[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashPlateString[playerid], 0);

dashOwnerString[playerid] = CreatePlayerTextDraw(playerid, 508.000000, 225.000000, "VOWNER");
PlayerTextDrawFont(playerid, dashOwnerString[playerid], 1);
PlayerTextDrawLetterSize(playerid, dashOwnerString[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, dashOwnerString[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, dashOwnerString[playerid], 1);
PlayerTextDrawSetShadow(playerid, dashOwnerString[playerid], 0);
PlayerTextDrawAlignment(playerid, dashOwnerString[playerid], 1);
PlayerTextDrawColor(playerid, dashOwnerString[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dashOwnerString[playerid], 255);
PlayerTextDrawBoxColor(playerid, dashOwnerString[playerid], 50);
PlayerTextDrawUseBox(playerid, dashOwnerString[playerid], 0);
PlayerTextDrawSetProportional(playerid, dashOwnerString[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dashOwnerString[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
