/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:accessDoor;

//Textdraws
accessDoor = TextDrawCreate(29.000000, 139.000000, "Access Door: SPACE");
TextDrawFont(accessDoor, 1);
TextDrawLetterSize(accessDoor, 0.491666, 1.900000);
TextDrawTextSize(accessDoor, 272.000000, 12.500000);
TextDrawSetOutline(accessDoor, 1);
TextDrawSetShadow(accessDoor, 0);
TextDrawAlignment(accessDoor, 1);
TextDrawColor(accessDoor, -1);
TextDrawBackgroundColor(accessDoor, 255);
TextDrawBoxColor(accessDoor, 50);
TextDrawUseBox(accessDoor, 1);
TextDrawSetProportional(accessDoor, 1);
TextDrawSetSelectable(accessDoor, 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
