// IORP Script
/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[3];
new randWeather;

public OnFilterScriptInit() {

    PublicTD[0] = TextDrawCreate(546.000000, 27.000000, ",");
    TextDrawFont(PublicTD[0], 1);
    TextDrawLetterSize(PublicTD[0], 0.012499, 3.699993);
    TextDrawTextSize(PublicTD[0], 613.000000, 17.000000);
    TextDrawSetOutline(PublicTD[0], 1);
    TextDrawSetShadow(PublicTD[0], 0);
    TextDrawAlignment(PublicTD[0], 1);
    TextDrawColor(PublicTD[0], -1);
    TextDrawBackgroundColor(PublicTD[0], 255);
    TextDrawBoxColor(PublicTD[0], 50);
    TextDrawUseBox(PublicTD[0], 1);
    TextDrawSetProportional(PublicTD[0], 1);
    TextDrawSetSelectable(PublicTD[0], 0);

    PublicTD[1] = TextDrawCreate(579.000000, 27.000000, "00-APR-19");
    TextDrawFont(PublicTD[1], 1);
    TextDrawLetterSize(PublicTD[1], 0.254165, 1.500000);
    TextDrawTextSize(PublicTD[1], 578.000000, 62.000000);
    TextDrawSetOutline(PublicTD[1], 1);
    TextDrawSetShadow(PublicTD[1], 0);
    TextDrawAlignment(PublicTD[1], 2);
    TextDrawColor(PublicTD[1], -1);
    TextDrawBackgroundColor(PublicTD[1], 255);
    TextDrawBoxColor(PublicTD[1], 50);
    TextDrawUseBox(PublicTD[1], 0);
    TextDrawSetProportional(PublicTD[1], 1);
    TextDrawSetSelectable(PublicTD[1], 0);

    PublicTD[2] = TextDrawCreate(580.000000, 44.000000, "00:00");
    TextDrawFont(PublicTD[2], 1);
    TextDrawLetterSize(PublicTD[2], 0.220831, 1.649999);
    TextDrawTextSize(PublicTD[2], 578.000000, 62.000000);
    TextDrawSetOutline(PublicTD[2], 1);
    TextDrawSetShadow(PublicTD[2], 0);
    TextDrawAlignment(PublicTD[2], 2);
    TextDrawColor(PublicTD[2], -1);
    TextDrawBackgroundColor(PublicTD[2], 255);
    TextDrawBoxColor(PublicTD[2], 50);
    TextDrawUseBox(PublicTD[2], 0);
    TextDrawSetProportional(PublicTD[2], 1);
    TextDrawSetSelectable(PublicTD[2], 0);

    TextDrawShowForAll(PublicTD[0]);
    TextDrawShowForAll(PublicTD[1]);
    TextDrawShowForAll(PublicTD[2]);

    print("Clock loaded");

    randWeather = random(20);
    SetWeather(randWeather);
    SetTimer("UpdateTimer", 1000, true);
    SetTimer("UpdateDate", 1000, true);
    SetTimer("ChangeWeather", 1800000, true);
    return 1;
}

forward public ChangeWeather();
public ChangeWeather(){
    randWeather = random(20);
    SetWeather(randWeather);
    return 1;
}

forward public UpdateDate();
public UpdateDate() {
    TextDrawHideForAll(PublicTD[0]);
    TextDrawHideForAll(PublicTD[1]);
    new year, month, day, Timestamp, Time[32], monthStr[4];
    Timestamp = getdate(year, month, day);
    switch (month) {
        case 1:            monthStr = "JAN";
        case 2:            monthStr = "FEB";
        case 3:            monthStr = "MAR";
        case 4:            monthStr = "APR";
        case 5:            monthStr = "MAY";
        case 6:            monthStr = "JUN";
        case 7:            monthStr = "JUL";
        case 8:            monthStr = "AUG";
        case 9:            monthStr = "SEP";
        case 10:            monthStr = "OCT";
        case 11:            monthStr = "NOV";
        case 12:            monthStr = "DEC";
    }    
    format(Time, sizeof(Time), "%02d-%s-%02d", day, monthStr, year);
    TextDrawSetString(PublicTD[1], Time);
    TextDrawShowForAll(PublicTD[0]);
    TextDrawShowForAll(PublicTD[1]);
    return 1;
}

forward public UpdateTimer();
public UpdateTimer() {
    TextDrawHideForAll(PublicTD[2]);
    new hour, mins, sec, Timestamp, Time[32];
    Timestamp = gettime(hour, mins, sec);
    format(Time, sizeof(Time), "%02d:%02d:%02d", hour, mins, sec);
    TextDrawSetString(PublicTD[2], Time);
    TextDrawShowForAll(PublicTD[2]);
    if(hour == 1){
        SetWorldTime(1);
    }
    if(hour == 2){
        SetWorldTime(2);      
    }
    if(hour == 3){
        SetWorldTime(3);
    }
    if(hour == 4){
        SetWorldTime(4);
    }
    if(hour == 5){        
        SetWorldTime(5);
    }
    if(hour == 6){
        SetWorldTime(6);      
    }
    if(hour == 7){
        SetWorldTime(7);       
    }
    if(hour == 8){
        SetWorldTime(8);      
    }
    if(hour == 9){
        SetWorldTime(9);      
    }
    if(hour == 10){
        SetWorldTime(10);    
    }
    if(hour == 11){
        SetWorldTime(11);        
    }
    if(hour == 12){
        SetWorldTime(12);      
    }
    if(hour == 13){
        SetWorldTime(13);        
    }
    if(hour == 14){
        SetWorldTime(14);      
    }
    if(hour == 15){
        SetWorldTime(15);       
    }
    if(hour == 16){
        SetWorldTime(16);       
    }
    if(hour == 17){
        SetWorldTime(17);       
    }
    if(hour == 18){
        SetWorldTime(18); 
    }
    if(hour == 19){
        SetWorldTime(19);         
    }
    if(hour == 20){
        SetWorldTime(20);       
    }
    if(hour == 21){
        SetWorldTime(21);       
    }
    if(hour == 22){
        SetWorldTime(22);
    }
    if(hour == 23){
        SetWorldTime(23);    
    }
    return 1;
}

public OnFilterScriptExit() {
    TextDrawDestroy(PublicTD[0]);
    TextDrawDestroy(PublicTD[1]);
    TextDrawDestroy(PublicTD[2]);
    return 1;
}

public OnPlayerConnect(playerid) {
    return 1;
}

public OnPlayerDisconnect(playerid) {
    return 1;
}

public OnPlayerCommandText(playerid, cmdtext[]) {
    if(!strcmp(cmdtext, "/tdtest", true)) {
        TextDrawShowForPlayer(playerid, PublicTD[0]);
        TextDrawShowForPlayer(playerid, PublicTD[1]);
        TextDrawShowForPlayer(playerid, PublicTD[2]);
        return 1;
    }
    return 0;
}